version: '3.1'
services:
  db:
    image: postgres
    container_name: postgre-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sis_demo
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sis-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sis_demo?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - db