apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deneme1.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "deneme1.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "deneme1.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname