apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  dbname: {{ .Values.env.postgres_db | b64enc }}
  username: {{ .Values.env.postgres_username | b64enc }}
  password: {{ .Values.env.postgres_password | b64enc }}