apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appsisdemo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "appsisdemo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "appsisdemo.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sis-config
                  key: spring_datasource_url